### ISSUE TITLE
Windows下执行会报错 'opt_type' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by ghost** [onetwo1/pinduoduo#1]
执行python pdd.py ,报错如下：
'opt_type' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'opt_name' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'opt_g' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'refer_page_name' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'refer_page_id' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'refer_page_sn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

解决方法:
将 https://github.com/onetwo1/pinduoduo/blob/87ee37436c71b14fb4a4bcf622e0995e27280cd2/pdd.py#L40
修改为 anti_content = os.popen(f'node merge.js "{referer_page_url}"').read().strip()
即可解决问题

**Comment by onetwo1** [comment]
windows 执行报错解决

**Comment by zhaoqiji** [comment]
你好，仍然报
function s_o(e = {}) {
                   ^
SyntaxError: Unexpected token =
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
的错误。您知道是什么原因造成的吗
