### ISSUE TITLE
有输入token，但运行pdd.py,直接返回以下报文。

### ISSUE THREAD

**Issue by gybgyb** [onetwo1/pinduoduo#10]
{"server_time":1556600325,"verify_auth_token":"bV3UnUHXQZrd4tI2-qH2gg","scene_id":11,"error_code":54001}

**Comment by qiyeboy** [comment]
我的也是这种情况，是不是加密 算法变化了呀，{"server_time":1556600325,"verify_auth_token":"bV3UnUHXQZrd4tI2-qH2gg","scene_id":11,"error_code":54001}
