### ISSUE TITLE
好像代理没有用，完全取决于宿主机ip

### ISSUE THREAD

**Issue by Snake-Dzh** [onetwo1/pinduoduo#8]
我用本机测试成功了，然后加上代理请求也是有效的，但是本机ip被封以后（翻页太快被封，要我登录）用代理也失效了，在服务器测试用不用代理都无效，这种除了登录有没有办法解决

**Comment by onetwo1** [comment]
不是没有用 是有代理池黑名单检测, 基本上市面上大部分的厂商的 ip 都是无效的 这跟淘宝的商品搜索接口是一样的

**Comment by Snake-Dzh** [comment]
@onetwo1 按理说请求是经过代理发出去，如果代理在黑名单那一定爬不到数据，但是我遇到的情况是本机ip不被封代理依然有效，**我是猜测是虽然用了代理，pdd还是能检测到宿主机的ip**，所有感觉代理没有起到作用
